### ISSUE TITLE
AWS_ERROR_DEST_COPY_TOO_SMALL with Iterable-Style Dataset

### ISSUE THREAD

**Issue by toma-novaprime** [awslabs/s3-connector-for-pytorch#194]
### s3torchconnector version

s3torchconnector-1.2.2

### s3torchconnectorclient version

s3torchconnectorclient-1.2.2

### AWS Region

us-east-2

### Describe the running environment

Running in a virtual environment (venv) on a Macbook Pro M3 Max, Sonoma 14.3.

I am using `Python 3.10.11`.

### What happened?

I am attempting to retrieve objects from s3 as part of my model training pipeline. For debugging purposes, I ran the following code, which worked initially, but ceased to work after a certain point. It's unclear to me what the cause of this Client error is.

For additional context, I have confirmed:
- The files exist on s3 and are not corrupted
- My credentials are correct and accessible (`aws s3 cp ...` works fine)
- The region is correct

```
iterable_dataset = S3IterableDataset.from_objects(
    object_uris=list_of_uris,
    region="us-east-2"
)

for i in iterable_dataset:
    bytes = bytearray(i.read())
    print(bytes)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/toma/src/project/src/mortgageml/datasets/fetch_data.py", line 47, in <module>
    print(i.read())
  File "/Users/toma/src/project/env/lib/python3.10/site-packages/s3torchconnector/s3reader.py", line 85, in read
    self._buffer.write(b"".join(self._stream))
s3torchconnectorclient._mountpoint_s3_client.S3Exception: Client error: Unknown CRT error: CRT error 26: aws-c-common: AWS_ERROR_DEST_COPY_TOO_SMALL, Destination of copy is too small.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by toma-novaprime** [comment]
@dnanuti @jamesbornholt Any thoughts on a potential resolution here? Is this connected to mountpoint?

**Comment by dnanuti** [comment]
Hi @toma-novaprime! Thank you for raising this!
We are using an S3 client wrapper [published by mountpoint-s3](https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-client-0.8.0). (*Please note that this crate is not intended for general-purpose use and we consider its interface to be unstable, as mentioned [here](https://crates.io/crates/mountpoint-s3-client)*). 

The underlying client is [AWS CRT](https://docs.aws.amazon.com/sdkref/latest/guide/common-runtime.html). At the first glance, the error you are experiencing is raised most probably from [here](https://github.com/search?q=repo%3Aawslabs%2Faws-c-common%20aws_raise_error(AWS_ERROR_DEST_COPY_TOO_SMALL)&type=code).

Before emitting any hypothesis, would you please be so kind to enable the debug logs and provide us the logs?
Setting these up and re-running the script should do the trick: 
```
  export S3_TORCH_CONNECTOR_DEBUG_LOGS=trace
  export S3_TORCH_CONNECTOR_LOGS_DIR_PATH="/tmp/s3torchconnector-logs"
```
More details about debug logging can be found in [our development guildelines](https://github.com/awslabs/s3-connector-for-pytorch/blob/main/doc/DEVELOPMENT.md#enabling-debug-logging).

Please note that this is outside business hours on my end, so you can expect an update on this next week. Thank you and have a nice weekend! 😄

**Comment by toma-novaprime** [comment]
Thank you for the prompt response, @dnanuti, and apologies for the late ping!

I've enabled verbose logging and have reproduced the issue. I am happy to provide the logs as needed however I am weary of potentially leaking sensitive information (bucket names, profiles, tokens-yet-to-expire, etc) so any specific guidance as to what you would need for diagnostic purposes would be greatly appreciated.

**Comment by toma-novaprime** [comment]
Looking through the logs I have discovered something curious, which may or may not warrant further investigation. Directly preceding the error message that I initially encountered, i.e.,
```
2024-03-22T23:33:59.252944Z ERROR awscrt::S3MetaRequest: id=0x102506c00: Request 0x10180af80 could not append to response body due to error 26 (Destination of copy is too small.)    
2024-03-22T23:33:59.252962Z ERROR awscrt::http-stream: id=0x101811ac0: Incoming body callback raised error 26 (AWS_ERROR_DEST_COPY_TOO_SMALL).    
2024-03-22T23:33:59.252978Z ERROR awscrt::http-connection: id=0x1018129e0: Message processing failed, error 26 (AWS_ERROR_DEST_COPY_TOO_SMALL). Closing connection.    
2024-03-22T23:33:59.252994Z  INFO awscrt::http-connection: id=0x1018129e0: Shutting down connection with error code 26 (AWS_ERROR_DEST_COPY_TOO_SMALL).   
```
are logs that seem to indicate that the s3 request was malformed (400) on account of the token having been expired.

```
2024-03-22T23:33:59.252482Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming response status: 400 (Bad Request).    
2024-03-22T23:33:59.252503Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: x-amz-request-id: Z21458MHZH6F1Y13    
2024-03-22T23:33:59.252530Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: x-amz-id-2: vOPu/IriAxoc5luIgP183nGwLxacl7KgXILwsZpvbLFujdRa7Xs8hcfe4c9u81cqSIK42gt69jDtdm3tsDuO5w==    
2024-03-22T23:33:59.252555Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: Content-Type: application/xml    
2024-03-22T23:33:59.252581Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: Transfer-Encoding: chunked    
2024-03-22T23:33:59.252608Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: Date: Fri, 22 Mar 2024 23:33:58 GMT    
2024-03-22T23:33:59.252633Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: Server: AmazonS3    
2024-03-22T23:33:59.252676Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming header: Connection: close    
2024-03-22T23:33:59.252703Z TRACE awscrt::http-stream: id=0x101811ac0: Received 'Connection: close' header. This will be the final stream on this connection.    
2024-03-22T23:33:59.252732Z TRACE awscrt::http-connection: id=0x1018129e0: Decoded 299 bytes of message, 0 bytes remain.    
2024-03-22T23:33:59.252757Z TRACE awscrt::channel: id=0x14670f110: acquired message 0x146864e00 of capacity 16384 from pool 0x600000034820. Requested size was 18446744073709551316    
2024-03-22T23:33:59.252804Z TRACE awscrt::tls-handler: id=0x1467106c0: bytes read 1152    
2024-03-22T23:33:59.252832Z TRACE awscrt::channel: id=0x14670f110: sending read message of size 1152, from slot 0x600002b78040 to slot 0x600002b08000 with handler 0x1018129e8.    
2024-03-22T23:33:59.252851Z TRACE awscrt::http-connection: id=0x1018129e0: Incoming message of size 1152.    
2024-03-22T23:33:59.252869Z TRACE awscrt::http-stream: id=0x101811ac0: Main header block done.    
2024-03-22T23:33:59.252886Z TRACE awscrt::http-stream: id=0x101811ac0: Incoming body: 1140 bytes received.    
2024-03-22T23:33:59.252905Z TRACE awscrt::S3MetaRequest: id=0x102506c00 Incoming body for request 0x10180af80. Response status: 400. Data Size: 1140. connection: 0x600003130ce0.    
2024-03-22T23:33:59.252922Z TRACE awscrt::S3MetaRequest: response body: 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0></Token-0><RequestId></RequestId><HostId></HostId></Error>
```
This is surprising because other ways of interacting with s3, like the AWS CLI, as mentioned previously, did *not* indicate that the token had expired or was invalid. Could it be then that the s3 connector had been using cached credentials instead of directly reading from `~/.aws/credentials`?

**Comment by dnanuti** [comment]
If you have static credentials set, i.e., `export AWS_ACCESS_KEY_ID=...`, `export AWS_SECRET_ACCESS_KEY=...` `export AWS_SESSION_TOKEN=...`, those will get picked up before the credentials file. 
[Here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#configure-precedence) are the official docs for the credentials precedence.

**Comment by dnanuti** [comment]
Hi, @toma-novaprime! 
I could not replicate your issue. Have you found the `AWS_ERROR_DEST_COPY_TOO_SMALL` in the logs?
What does this mean: "which worked initially, but ceased to work after a certain point"? Did it download a couple of items and stopped working in the same run?
How large is the dataset you are trying to load? Is there enough capacity to store the entire dataset in memory?

**Comment by dnanuti** [comment]
I managed to reproduce it using static credentials with an expired `AWS_SESSION_TOKEN`.

**Comment by IsaevIlya** [comment]
Hi, we are closing this issue as there was no response for a while. If you think that you are still experience that issue or have additional information on that case, please don't hesitate to reopen that issue.
